# Generated by Django 3.2.7 on 2021-09-17 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cd',
            old_name='label',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='vinyl',
            old_name='label',
            new_name='rating',
        ),
    ]
